spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: VGhpcy1pcy1hLXZlcnktc2VjcmV0LXNlY3JldC1rZXktd2hpY2gtaXMtbG9uZy1lbm91Z2gtZm9yLUhTNTEy # ??? ? secret key ????
  token-validity-in-seconds: 60 * 30

server:
  port: 8080