spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: D0BUrCTCH2C0ima4cy7k5hPATiO90GU8dDw8mBj6LfAu07+BVkueaknyKqfQ6m+wKqCfVfNxaAnK2sJAhZlV4w==
  token-validity-in-seconds: 1800

server:
  port: 8080